services:
  imgs:
    image: nginx:1-alpine
    ports:
      - 8888:80
    volumes:
      - ./capture/:/usr/share/nginx/html
  ui:
    build: ./ui/.
    ports:
      - "6600:3000"
    volumes:
      - .:/ui
      - /ui/node_modules
    stdin_open: true
    tty: true
  # api:
  #   build: ./api
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - type: bind
  #       source: api/database.sqlite
  #       target: /opt/app/database.sqlite
  #   ports:
  #     - "5555:3300"